---
# tasks file for openssl_build
- name: "Validation"
  assert:
    that:
      - "'{{ openssl_build_version | regex_replace('^(\\d+\\.\\d+\\.\\d+)[a-z]?', '\\1') }}' == '1.1.1'"
      - "'{{ ansible_distribution }}' in ['CentOS', 'RedHat']"

- when: ansible_distribution == 'CentOS'
  name: "Validation for CentOS"
  assert:
    that:
      - "'{{ ansible_distribution_major_version }}' in ['7', '8']"

- when: ansible_distribution == 'RedHat'
  name: "Validation for RedHat"
  assert:
    that:
      - "'{{ ansible_distribution_major_version }}' in ['8']"

- name: "Install required packages"
  yum:
    name: "{{ openssl_build_required_packages }}"
    state: present

- name: Remove OpenSSL source
  ansible.builtin.file:
    path: "{{ openssl_build_src_path }}"
    state: absent
  changed_when: false

- when: not openssl_build_unarchive_remote_src
  name: Create temporary download directory
  local_action:
    module: tempfile
    state: directory
  register: openssl_build_temp_download_dir
  changed_when: false

- when: not openssl_build_unarchive_remote_src
  name: "Download OpenSSL sources to local"
  local_action:
    module: get_url
    url: "{{ openssl_build_src_url }}"
    dest: "{{ openssl_build_temp_download_dir.path }}"
  register: openssl_build_temp_download_file
  changed_when: false

- name: "Unarchive OpenSSL source"
  unarchive:
    src: "{% if not openssl_build_unarchive_remote_src %}{{ openssl_build_temp_download_file.dest }}{% else %}{{ openssl_build_src_url }}{% endif %}"
    dest: "{{ openssl_build_unarchive_dest }}"
    remote_src: "{{ openssl_build_unarchive_remote_src }}"
  changed_when: false

- when: not openssl_build_unarchive_remote_src
  name: "Delete downloaded OpenSSL sources to local"
  local_action:
    module: file
    path: "{{ openssl_build_temp_download_dir.path }}"
    state: absent
  changed_when: false

- name: "Execute OpenSSL config"
  command:
    cmd: "./config{% if openssl_build_config_option %} {{ openssl_build_config_option | join(' ') }}{% endif %}"
    chdir: "{{ openssl_build_src_path }}"
  changed_when: false

- name: "Execute OpenSSL make"
  community.general.make:
    chdir: "{{ openssl_build_src_path }}"
    target: "{{ item }}"
  changed_when: false
  loop: "{{ openssl_build_make_target }}"
